name: 'Latest deployment sha'
description: 'Get sha of latest active deployment'
author: 'Nithin'
branding:
  icon: box
  color: purple

# Define your inputs here.
inputs:
  repo_owner:
    description: 'Repo owner'
    required: true
  repo_name:
    description: 'Repo name'
    required: true
  environment:
    description: 'Deployment environment'
    required: true
  branch:
    description: 'Filter by the branch'
    default: 'main'
    required: true

# Define your outputs here.
outputs:
  sha:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
